//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public Customers()
        {
            this.Purchases = new HashSet<Purchases>();
        }
    
        public int Id { get; set; }
        public string CustomerName { get; set; }
    
        public virtual ICollection<Purchases> Purchases { get; set; }
    }
}
